name: 'Code review action'
author: jimyx
inputs:
  metric:
    description: 'Metric type'
  m0:
    description: 'M0'
  m1:
    description: 'M1'
  m2:
    description: 'M2'
  m3:
    description: 'M3'
  m4:
    description: 'M4'
  m5:
    description: 'M5'
  pullRequestId:
    description: 'Pull request ID'
output:
  value:
    description: 'Record'
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'alert-triangle'
  color: 'gray-dark'