name: 'Code review action'
author: jimyx
inputs:
  word:
    description: 'My param'
    defult: 'none'
output:
  result:
    description: 'My output param'
    default: 'none'
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'alert-triangle'
  color: 'gray-dark'